name: Docker tests
#Should be done with sending image to the docker registry and uploading artifacts to the S3 instead of using bind-mounts
on:
  push:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      # checkout application code
      - uses: actions/checkout@v2
      # build application Docker image
      - name: Build image
        run: docker build . -t test-image
      # run application Docker image
      - name: Start container with tests
        run: docker run test-image:latest -it --mount type=bind,source=$PWD/test-results,target=/app/test-results
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 7
