name: Tests

on:
  push:
    branches: [main]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      # checkout application code
      - uses: actions/checkout@v2
      # build application Docker image
      - name: Build image
        run: docker build . -t test-image
      # run application Docker image
      - name: Start container (application)
        run: docker run test-image --rm
